### ISSUE TITLE
Node.JS

### ISSUE THREAD

**Issue by majimboo** [maryrosecook/machinejs#3]
Can I use this with node.js? I'm getting:

```
var Machine = Base.extend({
                 ^
TypeError: Object #<Object> has no method 'extend'
```

With the demo.

**Comment by maryrosecook** [comment]
I’m afraid it’s not compatible with node.  I plan to rewrite it so it will run in both the browser and on node, but I’m not sure when I will get around to it, I’m afraid.

Mary

—
http://maryrosecook.com http://maryrosecook.com/

**Comment by majimboo** [comment]
I forked and was actually able to fix it to be compatible with node.

Just added the base.js to the project folder, required it to the `machine.js` file. Then changed `window['Machine'] = Machine;` to `module.exports = Machine` and you're good to go for node.

**Comment by maryrosecook** [comment]
Great.  I'm glad you got it working.  I think when I rewrite it I will omit Base, so I won't make any changes to support node for now.

Thanks again!
